title: Apollo Android Guide
subtitle: Apollo Android Guide
versions:
  - '1'
sidebar_categories:
  null:
    - index
  Essentials:
      - essentials/get-started
      - essentials/queries
github_repo: apollographql/apollo-android
content_root: docs/source

url: https://www.apollographql.com/docs/android
root: /docs/android/

public_dir: public/docs/android

