name: platform-api-tests

on:
  #  pull_request:
  #    branches: [ '*' ]
  schedule:
    - cron: '0 3 * * *'
  workflow_dispatch:

env:
  GRADLE_ENTERPRISE_ACCESS_KEY: ${{ secrets.GRADLE_ENTERPRISE_ACCESS_KEY }}

jobs:
  platform-api-tests:
    runs-on: macos-11
    if: github.repository == 'apollographql/apollo-kotlin'
    steps:
      - name: Checkout project
        uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c #v3.3.0

      - name: Setup Java
        uses: actions/setup-java@1df8dbefe2a8cbc99770194893dd902763bee34b #v3.9.0
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Setup Gradle
        uses: gradle/gradle-build-action@3fbe033aaae657f011f88f29be9e65ed26bd29ef #v2.3.3

      - name: Run tests against the Apollo Platform API
        env:
          PLATFORM_API_TESTS_KEY: ${{ secrets.PLATFORM_API_TESTS_KEY }}
        run: |
          ./gradlew -p tests --no-daemon --console plain :platform-api:registerServiceApolloOperations
          ./gradlew -p tests --no-daemon --console plain :platform-api:downloadServiceApolloSchemaFromRegistry
          ./gradlew -p tests --no-daemon --console plain :platform-api:pushApolloSchema --key=$PLATFORM_API_TESTS_KEY --subgraph=subgraph1 --schema=platform-api/src/main/graphql/schema.graphqls --revision=1 --graphVariant=current
