name: Publish IntelliJ plugin snapshot

on:
#  pull_request:
  #    branches: [ '*' ]
  schedule:
    - cron: '0 0 * * 0'
env:
  GRADLE_ENTERPRISE_ACCESS_KEY: ${{ secrets.GRADLE_ENTERPRISE_ACCESS_KEY }}

jobs:
  publish-intellij-plugin:
    name: Publish IntelliJ plugin
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c #v3.3.0

      - uses: actions/setup-java@1df8dbefe2a8cbc99770194893dd902763bee34b #v3.9.0
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Increment snapshot version
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          ./scripts/increment-ij-plugin-snapshot.main.kts
        env:
          COM_APOLLOGRAPHQL_IJ_PLUGIN_SNAPSHOT: true
          GH_TOKEN: ${{ github.token }}

      - name: Publish snapshot to Repsy
        run: ./gradlew --no-build-cache :intellij-plugin:publishAllPublicationsToRepsyIjPluginSnapshots
        env:
          COM_APOLLOGRAPHQL_IJ_PLUGIN_SNAPSHOT: true
          IJ_PLUGIN_REPSY_USERNAME: ${{ secrets.IJ_PLUGIN_REPSY_USERNAME }}
          IJ_PLUGIN_REPSY_PASSWORD: ${{ secrets.IJ_PLUGIN_REPSY_PASSWORD }}
